//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssertusApp.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int ContactID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(10)]
        //[RegularExpression(@"^\(\d{3}\)\s{0,1}\d{3}-\d{7}$", ErrorMessage = "Enter a valid number")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
       
        [StringLength(10)]
        //[RegularExpression(@"^\(\d{3}\)\s{0,1}\d{3}-\d{7}$", ErrorMessage = "Enter a valid number")]
        [DataType(DataType.PhoneNumber)]
        public string Fax { get; set; }
        [StringLength(50)]

        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string eMail { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateUserName { get; set; }
    }
}
